databases:
  - name: homeworkplanner
    databaseName: homeworkplanner
    user: homeworkplanner

services:
  - type: web
    name: homeworkplanner
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: homeworkplanner
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false