databases:
  - name: assignmentplanner
    databaseName: assignmentplanner
    user: assignmentplanner

services:
  - type: web
    name: assignmentplanner
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: assignmentplanner
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false